

###
GET http://localhost:3000/subscriptions
Content-Type: application/json

###

POST http://localhost:3000/subscriptions
Content-Type: application/json

{
  "user_id":2,
  "code":"12346",
  "amount":102,
  "cron":"2"
}

###
### crear una entrada de dinero
POST http://localhost:3000/movements
Content-Type: application/json

{
  "type": 0,
  "amount": 100,
  "user_id": 1
}

### listar todos los moviemeintos
GET http://localhost:3000/movements
Content-Type: application/json

### listar un moviemnto por id de moviemnto
GET http://localhost:3000/movements/1
Content-Type: application/json


